#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Tue Jan 20 07:13:47 2015
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
import gettext
from WiznetConfig_GUI import WiznetConfig_GUI

class WiznetGUI(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        main_frame = WiznetConfig_GUI(None, wx.ID_ANY, "")
        self.SetTopWindow(main_frame)
        main_frame.Show()
        return 1

# end of class WiznetGUI

if __name__ == "__main__":
    gettext.install("wiznet_GUI") # replace with the appropriate catalog name

    wiznet_GUI = WiznetGUI(0)
    wiznet_GUI.MainLoop()