# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Tue Jan 20 07:13:47 2015
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class WiznetConfig_GUI(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: WiznetConfig_GUI.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.ltbWizList = wx.ListBox(self, wx.ID_ANY, choices=[])
        self.lbtStatus = wx.ListBox(self, wx.ID_ANY, choices=[])
        self.btnSearch = wx.BitmapButton(self, wx.ID_ANY, 
            wx.Bitmap("/home/maestro/Workspace/wiznet_conf/icons/zoom77.png", 
                wx.BITMAP_TYPE_ANY), style=wx.NO_BORDER)
        self.btnSetup_copy = wx.BitmapButton(self, wx.ID_ANY, 
            wx.Bitmap("/home/maestro/Workspace/wiznet_conf/icons/equalizer3.png", 
                wx.BITMAP_TYPE_ANY), style=wx.NO_BORDER)
        self.btnPing_copy = wx.BitmapButton(self, wx.ID_ANY, 
            wx.Bitmap("/home/maestro/Workspace/wiznet_conf/icons/check61.png", 
                wx.BITMAP_TYPE_ANY), style=wx.NO_BORDER)
        self.btnUpload_copy = wx.BitmapButton(self, wx.ID_ANY, 
            wx.Bitmap("/home/maestro/Workspace/wiznet_conf/icons/uparrow15.png", 
                wx.BITMAP_TYPE_ANY), style=wx.NO_BORDER)
        self.btnExit = wx.BitmapButton(self, wx.ID_ANY, 
            wx.Bitmap("/home/maestro/Workspace/wiznet_conf/icons/power18.png", 
                wx.BITMAP_TYPE_ANY), style=wx.NO_BORDER)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: WiznetConfig_GUI.__set_properties
        self.SetTitle(_("Herramienta de Configuracion para Wiznet WIZ110SR"))
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("/home/maestro/Workspace/wiznet_conf/icons/settings48.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((600, 420))
        self.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.ltbWizList.SetMinSize((250, 400))
        self.ltbWizList.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.ltbWizList.SetForegroundColour(wx.Colour(1, 1, 1))
        self.lbtStatus.SetMinSize((250, 400))
        self.lbtStatus.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.lbtStatus.SetForegroundColour(wx.Colour(1, 1, 1))
        self.btnSearch.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.btnSearch.SetToolTipString(_("Buscar"))
        self.btnSearch.SetSize(self.btnSearch.GetBestSize())
        self.btnSetup_copy.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.btnSetup_copy.SetToolTipString(_("Configurar"))
        self.btnSetup_copy.SetSize(self.btnSetup_copy.GetBestSize())
        self.btnPing_copy.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.btnPing_copy.SetToolTipString(_("Ping"))
        self.btnPing_copy.SetSize(self.btnPing_copy.GetBestSize())
        self.btnUpload_copy.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.btnUpload_copy.SetToolTipString(_("Cargar Firmware"))
        self.btnUpload_copy.SetSize(self.btnUpload_copy.GetBestSize())
        self.btnExit.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.btnExit.SetToolTipString(_("Salir"))
        self.btnExit.SetSize(self.btnExit.GetBestSize())
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: WiznetConfig_GUI.__do_layout
        grid_sizer_1 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_2 = wx.FlexGridSizer(8, 1, 0, 0)
        grid_sizer_1.Add(self.ltbWizList, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.lbtStatus, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.btnSearch, 0, wx.ALL, 5)
        grid_sizer_2.Add(self.btnSetup_copy, 0, wx.ALL, 5)
        grid_sizer_2.Add(self.btnPing_copy, 0, wx.ALL, 5)
        grid_sizer_2.Add(self.btnUpload_copy, 0, wx.ALL, 5)
        grid_sizer_2.Add(self.btnExit, 0, wx.ALL, 5)
        grid_sizer_2.AddGrowableCol(0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.AddGrowableCol(0)
        grid_sizer_1.AddGrowableCol(1)
        grid_sizer_1.AddGrowableCol(2)
        self.Layout()
        # end wxGlade

# end of class WiznetConfig_GUI
